"""cria tabelas importacoes e itens

Revision ID: 8d0fc433e692
Revises:
Create Date: 2026-08-14 11:08:01.688756

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d0fc433e692"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "importacoes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("numero_fatura", sa.String(length=64), nullable=False),
        sa.Column("fornecedor", sa.String(length=160), nullable=False),
        sa.Column("valor_total_usd", sa.Float(), nullable=False),
        sa.Column("peso_bruto_kg", sa.Float(), nullable=False),
        sa.Column("incoterm", sa.String(length=8), nullable=False),
        sa.Column("volumes", sa.Integer(), nullable=False),
        sa.Column("moeda", sa.String(length=3), nullable=False),
        sa.Column("ncm_sugerido", sa.String(length=16), nullable=True),
        sa.Column("prazo_estimado_dias", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload_bruto", sa.JSON(), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("data_criacao", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_atualizacao", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_fatura", "fornecedor", name="uq_importacao_fatura_fornecedor"),
    )
    op.create_index(
        op.f("ix_importacoes_numero_fatura"), "importacoes", ["numero_fatura"], unique=False
    )
    op.create_index(op.f("ix_importacoes_status"), "importacoes", ["status"], unique=False)
    op.create_table(
        "itens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("importacao_id", sa.Integer(), nullable=False),
        sa.Column("ncm", sa.String(length=16), nullable=True),
        sa.Column("descricao", sa.String(length=255), nullable=False),
        sa.Column("quantidade", sa.Float(), nullable=False),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_itens_importacao_id"), "itens", ["importacao_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_itens_importacao_id"), table_name="itens")
    op.drop_table("itens")
    op.drop_index(op.f("ix_importacoes_status"), table_name="importacoes")
    op.drop_index(op.f("ix_importacoes_numero_fatura"), table_name="importacoes")
    op.drop_table("importacoes")
    # ### end Alembic commands ###
